### ISSUE TITLE
Add sbt-docker-compose

### ISSUE THREAD

**Issue by Fristi** [fullfacing/keycloak4s#55]
Such that we can test PR's with Travis or CircleCI

**Comment by Fristi** [comment]
I used ehsanyou/sbt-docker-compose with the version from https://github.com/ehsanyou/sbt-docker-compose/pull/10
`addSbtPlugin("com.github.ehsanyou" % "sbt-docker-compose" % "67284e73-envvars-2m")`

The reason for using this sbt-docker-compose version is since the Tapad plugin doesn't support health checks in docker-compose which can be used to verify if Keycloak is up:

```
  keycloak:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1s
      timeout: 5s
      retries: 30
```
